default: &default
  adapter: "mysql2"
  encoding: "utf8mb4"
  database: <%= ENV.fetch("MARIADB_DB") { "gitee-grimoirelab" } %>
  username: <%= ENV.fetch("MARIADB_USER") { "gitee-grimoirelab" } %>
  password: <%= ENV.fetch("MARIADB_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("MARIADB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("MARIADB_PORT") { 3306 } %>
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("MARIADB_DB") { "gitee-grimoirelab_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("MARIADB_DB") { "gitee-grimoirelab_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("MARIADB_DB") { "gitee-grimoirelab_production" } %>
